# Generated by Django 5.0.7 on 2024-09-05 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AooHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="AOO開催タイトル"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
            ],
            options={
                "db_table": "AOO_HOLD",
            },
        ),
        migrations.CreateModel(
            name="AooRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aoo_title",
                    models.CharField(max_length=20, verbose_name="AOO開催タイトル"),
                ),
                ("user_name", models.CharField(max_length=20, verbose_name="ユーザ名")),
                (
                    "user_participation",
                    models.BooleanField(blank=True, null=True, verbose_name="参加可否"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
            ],
            options={
                "db_table": "AOO_REGISTER",
            },
        ),
    ]
