# Generated by Django 5.0.7 on 2024-09-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_aoohold_aooregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aooregister",
            name="aoo_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.aoohold",
                verbose_name="AOO開催タイトル",
            ),
        ),
    ]
