# Generated by Django 5.0.7 on 2024-09-05 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_aooregister_aoo_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aooregister",
            old_name="aoo_title",
            new_name="aoo_id",
        ),
    ]
